name: Integration test on Azure

on: repository_dispatch
jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    container:
      image: 'aztfmod/rover:2001.2205'
      options: --user 0
    steps:
    - uses: actions/checkout@v2
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_2  }}
    - name: Terraform Validate
      run: |
        cd examples/rg_simple
        terraform validate -no-color
      shell: bash
    - name: Terraform Plan
      run: |
        cd examples/rg_simple
        terraform plan -no-color
      shell: bash
    - name: Terraform apply
      run: |
        cd examples/rg_simple
        terraform apply -no-color -auto-approve
      shell: bash
