name: Integration test on Azure

on: repository_dispatch
jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    container: 'aztfmod/rover:2001.2205'
    options: --user 0
    steps:
    - uses: actions/checkout@v2
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - name: Terraform Validate
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          cd examples/rg_simple
          terraform validte -no-color
    - name: Terraform Plan
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          cd examples/rg_simple
          terraform plan -no-color
    - name: Terraform apply
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          cd examples/rg_simple
          terraform apply -no-color -auto-approve
