name: Integration test on Azure

on: repository_dispatch
jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    container:
      image: 'aztfmod/rover:2001.2205'
      options: --user 0
    steps:
    - uses: actions/checkout@v2
   # Authentication
    - name: Terraform configure ARM
      run: |
        export ARM_CLIENT_ID=$(echo ${{ secrets.AZURE_CREDENTIALS_2  }} | jq ".clientId")
        export ARM_CLIENT_SECRET=$(echo ${{ secrets.AZURE_CREDENTIALS_2  }} | jq ".clientSecret")
        export ARM_SUBSCRIPTION_ID=$(echo ${{ secrets.AZURE_CREDENTIALS_2  }} | jq ".subscriptionId")
        export ARM_TENANT_ID=$(echo ${{ secrets.AZURE_CREDENTIALS_2  }} | jq ".tenantId")
      shell: bash
    - name: Terraform Validate
      run: |
        cd examples/rg_simple
        terraform init
        terraform validate -no-color
      shell: bash
    - name: Terraform Plan
      run: |
        cd examples/rg_simple
        terraform plan -no-color
      shell: bash
    - name: Terraform apply
      run: |
        cd examples/rg_simple
        terraform apply -no-color -auto-approve
      shell: bash
