name: Integration test on Azure

on:
  release:
    types: [published]



jobs:
  deploy-to-azure:
    runs:
      using: 'docker'
      image: 'aztfmod/rover:2001.2205'
    steps:
    - uses: actions/checkout@v2
            
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - name: Terraform Validate
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          cd examples/rg_simple
          terraform validte -no-color
    - name: Terraform Plan
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          terraform plan -no-color
    - name: Terraform apply
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          terraform apply -no-color -auto-approve
  
  validate-deployment-azure:
    needs: [deploy-to-azure]
    runs:
      using: 'docker'
      image: 'aztfmod/rover:2001.2205'
    steps:  
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - name: Terraform Validate
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          #TODO right scripts
   